### ISSUE TITLE
Integrity checker disabled?

### ISSUE THREAD

**Issue by fBedecarrats** [syncloud/nextcloud#4]
Hello,
I've recently set up a RPi3 with Syncloud and installed Nextcloud app. Congratulations for this wonderfull job!!!
Nextcloud app is working, but when I go to the Administration menu, the right panel starts with an error message saying: 
> "Some files did not pass integrity checks. More information on how to solve this problem in our documentation. (List of invalid files... / Relaunch)."

When I click List of invalid files, I get: 
> Integrity checker has been disabled. Integrity cannot be verified.

Best regards,
FB

**Comment by cyberb** [comment]
We track this issue here: https://github.com/syncloud/platform/issues/149
It happens because we had to fix huge file upload in ownCloud/nextcloud code and they sign the code now to detect code changes.
They accepted our fix but haven't released it yet, also as nextcloud fork lives its own life I am not sure what happened to the patch.
Anyway this is not critical warning.
